### ISSUE TITLE
error when a new device is added and accessed

### ISSUE THREAD

**Issue by floored1585** [floored1585/pixel#41]
App 54376 stderr: 2016-10-12 17:48:06 - NoMethodError - undefined method `>=' for nil:NilClass:
App 54376 stderr: 	/var/www/pixel/releases/20160909193332/lib/helper.rb:298:in `number_to_human'
App 54376 stderr: 	/var/www/pixel/releases/20160909193332/views/device.erb:38:in `block in singleton class'
App 54376 stderr: 	/var/www/pixel/releases/20160909193332/views/device.erb:-11:in `instance_eval'
App 54376 stderr: 	/var/www/pixel/releases/20160909193332/views/device.erb:-11:in `singleton class'
App 54376 stderr: 	/var/www/pixel/releases/20160909193332/views/device.erb:-13:in `__tilt_32826720'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/tilt-2.0.2/lib/tilt/template.rb:164:in `call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/tilt-2.0.2/lib/tilt/template.rb:164:in `evaluate'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/tilt-2.0.2/lib/tilt/template.rb:99:in `render'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:823:in `render'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:667:in `erb'
App 54376 stderr: 	/var/www/pixel/releases/20160909193332/routes/html.rb:110:in `block in <class:Pixel>'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1610:in `call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1610:in `block in compile!'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/rack-coffee-1.0.3/lib/rack/coffee.rb:89:in `call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
App 54376 stderr: 	/var/www/pixel/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
App 54376 stderr: 	/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
App 54376 stderr: 	/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
App 54376 stderr: 	/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
App 54376 stderr: 	/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
App 54376 stderr: 	/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by floored1585** [comment]
Closed with commit 382dba9
